-- V6.0: Add campaign_bible_json column to campaigns table.
-- Stores the full CampaignBibleOutput generated by CampaignBibleAgent at setup time.
-- This is the campaign's screenplay bible: locations, NPC cast, companions, factions,
-- and quest arcs — all tailored to the player's concept and chosen Legends timeline date.
-- Replaces the static era pack YAML content (companions.yaml, npcs.yaml, factions.yaml, etc.)
-- NULL until campaign setup completes (legacy campaigns remain NULL and fall back to defaults).
ALTER TABLE campaigns ADD COLUMN campaign_bible_json TEXT;
