# -*- coding: utf-8 -*-
"""
Merge 64 new NPCs into New Republic era pack
Phase 2 of enrichment: Add canonical EU anchors, officers, Remnant, Jedi, frontier leaders, merchants, templates
"""

import yaml
import sys

def main():
    # Read existing file
    with open('data/static/era_packs/new_republic/npcs.yaml', 'r', encoding='utf-8') as f:
        data = yaml.safe_load(f)

    npcs = data['npcs']
    initial_count = sum(len(v) for v in npcs.values() if isinstance(v, list))
    print(f"Starting with {initial_count} NPCs")

    # Canonical anchors (adding 10 more - already added 2, need 10 more for 12 total new)
    additional_anchors = [
        {"id": "npc_callista_ming", "name": "Callista Ming", "rarity": "rare", "aliases": ["Callista", "Lost Jedi"], "faction_id": "jedi_order", "role": "Jedi Knight", "archetype": "Force User", "traits": ["Mysterious", "Skilled", "Troubled"], "motivation": "Restore herself and reclaim Jedi identity", "secret": "Struggles with loss of Force connection", "voice_tags": ["thoughtful", "melancholic"], "default_location_id": "loc-yavin_praxeum", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 2, "can_grant_access": ["jedi_academy"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_garm_bel_iblis", "name": "Garm Bel Iblis", "rarity": "unique", "aliases": ["Admiral Bel Iblis"], "faction_id": "new_republic", "role": "Military Admiral", "archetype": "Strategist", "traits": ["Independent", "Cunning", "Proud"], "motivation": "Ensure New Republic military strength", "secret": "Questions civilian leadership", "voice_tags": ["commanding", "gruff"], "default_location_id": "loc-fleet_base_orbital", "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 4, "can_grant_access": ["military_command"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_hiram_drayson", "name": "Admiral Hiram Drayson", "rarity": "unique", "aliases": ["Admiral Drayson"], "faction_id": "new_republic", "role": "Intelligence Director", "archetype": "Spymaster", "traits": ["Pragmatic", "Secretive", "Thorough"], "motivation": "Protect New Republic through intelligence", "secret": "Operates beyond official Republic oversight", "voice_tags": ["measured", "vague"], "default_location_id": "loc-coruscant", "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 5, "can_grant_access": ["nri_operations"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_soontir_fel", "name": "Soontir Fel", "rarity": "unique", "aliases": ["Baron Fel"], "faction_id": "imperial_remnant", "role": "Military Commander", "archetype": "Pilot", "traits": ["Proud", "Skilled", "Stubborn"], "motivation": "Restore Imperial glory", "secret": "Doubts Remnant viability", "voice_tags": ["commanding", "formal"], "default_location_id": "loc-bastion", "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 4, "can_grant_access": ["imperial_military"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_leia_organa_solo", "name": "Leia Organa Solo", "rarity": "unique", "aliases": ["Chief of State"], "faction_id": "new_republic", "role": "Political Leader", "archetype": "Diplomat", "traits": ["Decisive", "Principled", "Wise"], "motivation": "Build lasting peace", "secret": "Carries weight of billions-scale decisions", "voice_tags": ["diplomatic", "commanding"], "default_location_id": "loc-coruscant", "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 5, "can_grant_access": ["senate"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_mon_mothma", "name": "Mon Mothma", "rarity": "unique", "aliases": ["Admiral Mothma"], "faction_id": "new_republic", "role": "Military Admiral", "archetype": "Strategist", "traits": ["Careful", "Strategic", "Diplomatic"], "motivation": "Ensure Republic stability", "secret": "Concerns about long-term viability", "voice_tags": ["diplomatic", "measured"], "default_location_id": "loc-coruscant", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 5, "can_grant_access": ["senate", "military_command"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_wedge_antilles", "name": "Wedge Antilles", "rarity": "unique", "aliases": ["General Antilles"], "faction_id": "new_republic", "role": "Military General", "archetype": "Pilot", "traits": ["Skilled", "Brave", "Principled"], "motivation": "Protect Republic and train pilots", "secret": "Struggles with war losses", "voice_tags": ["earnest", "commanding"], "default_location_id": "loc-chandrila_academy", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 4, "can_grant_access": ["military_command"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_talon_karrde", "name": "Talon Karrde", "rarity": "unique", "aliases": ["Smuggler Lord"], "faction_id": "smugglers_alliance", "role": "Smuggling Lord", "archetype": "Scoundrel", "traits": ["Cunning", "Pragmatic", "Connected"], "motivation": "Maintain smuggling empire", "secret": "Has leverage over both NR and Remnant", "voice_tags": ["formal", "calculated"], "default_location_id": "loc-myrkr", "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["smuggler_network"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    ]

    npcs['anchors'].extend(additional_anchors)
    print(f"Added {len(additional_anchors)} more anchors. Total anchors: {len(npcs['anchors'])}")

    # Now add rotating NPCs (officers, Remnant, Jedi, frontier, merchants - ~50 NPCs)
    rotating_npcs = [
        # NR Officers & Diplomats (15)
        {"id": "npc_colonel_jax_pavan", "name": "Colonel Jax Pavan", "rarity": "rare", "aliases": ["Colonel Pavan"], "faction_id": "new_republic", "role": "Military Officer", "archetype": "Soldier", "traits": ["Disciplined", "Loyal", "Professional"], "motivation": "Serve Republic faithfully", "secret": "Harbors doubts about military leadership", "voice_tags": ["formal", "earnest"], "default_location_id": "loc-fleet_base_orbital", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 2, "can_grant_access": ["military_base"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_captain_ryx_monn", "name": "Captain Ryx Monn", "rarity": "rare", "aliases": ["Captain Monn"], "faction_id": "new_republic", "role": "Fleet Commander", "archetype": "Pilot", "traits": ["Skilled", "Cautious", "Strategic"], "motivation": "Protect New Republic assets", "secret": "Has connection to Imperial defectors", "voice_tags": ["measured", "formal"], "default_location_id": "loc-mon_calamari_yards", "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 2, "can_grant_access": ["fleet_operations"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_senator_delvardus", "name": "Senator Delvardus", "rarity": "rare", "aliases": ["Senator"], "faction_id": "new_republic", "role": "Senate Member", "archetype": "Politician", "traits": ["Ambitious", "Eloquent", "Calculating"], "motivation": "Advance personal power", "secret": "Takes bribes from corporate interests", "voice_tags": ["diplomatic", "persuasive"], "default_location_id": "loc-coruscant", "levers": {"bribeable": True, "intimidatable": True, "charmable": True}, "authority": {"clearance_level": 2, "can_grant_access": ["senate"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_diplomat_teela_mon", "name": "Diplomat Teela Mon", "rarity": "rare", "aliases": ["Teela"], "faction_id": "new_republic", "role": "Diplomat", "archetype": "Negotiator", "traits": ["Perceptive", "Patient", "Principled"], "motivation": "Negotiate peace and alliances", "secret": "Falls in love with those she negotiates with", "voice_tags": ["diplomatic", "thoughtful"], "default_location_id": "loc-coruscant", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 2, "can_grant_access": ["diplomatic_missions"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_commander_vereti_ginn", "name": "Commander Vereti Ginn", "rarity": "rare", "aliases": ["Commander Ginn"], "faction_id": "new_republic", "role": "Military Commander", "archetype": "Soldier", "traits": ["Decisive", "Authoritative", "Fair"], "motivation": "Lead troops effectively", "secret": "Covers up soldier casualties", "voice_tags": ["commanding", "earnest"], "default_location_id": "loc-fleet_base_orbital", "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 2, "can_grant_access": ["military_command"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_lieutenant_myn_donos", "name": "Lieutenant Myn Donos", "rarity": "rare", "aliases": ["Lieutenant Donos"], "faction_id": "new_republic", "role": "Military Officer", "archetype": "Pilot", "traits": ["Skilled", "Determined", "Haunted"], "motivation": "Become best pilot", "secret": "Feels responsible for lost squadron", "voice_tags": ["earnest", "determined"], "default_location_id": "loc-chandrila_academy", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["pilot_training"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_ambassador_dinn_vouv", "name": "Ambassador Dinn Vouv", "rarity": "rare", "aliases": ["Ambassador Vouv"], "faction_id": "new_republic", "role": "Diplomat", "archetype": "Negotiator", "traits": ["Charming", "Eloquent", "Ambitious"], "motivation": "Expand Republic influence", "secret": "Reports to intelligence agencies", "voice_tags": ["diplomatic", "persuasive"], "default_location_id": "loc-coruscant", "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 2, "can_grant_access": ["diplomatic_missions"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_captain_horrsk", "name": "Captain Horrsk", "rarity": "rare", "aliases": ["Captain"], "faction_id": "new_republic", "role": "Fleet Captain", "archetype": "Pilot", "traits": ["Disciplined", "Tactical", "Stern"], "motivation": "Maintain fleet discipline", "secret": "Has romantic involvement with subordinate", "voice_tags": ["commanding", "formal"], "default_location_id": "loc-fleet_base_orbital", "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 2, "can_grant_access": ["fleet_operations"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_commodore_evir_derricote", "name": "Commodore Evir Derricote", "rarity": "rare", "aliases": ["Commodore Derricote"], "faction_id": "new_republic", "role": "Fleet Officer", "archetype": "Pilot", "traits": ["Ambitious", "Cunning", "Ruthless"], "motivation": "Achieve high rank", "secret": "Has sabotaged competitors", "voice_tags": ["calculating", "formal"], "default_location_id": "loc-mon_calamari_yards", "levers": {"bribeable": True, "intimidatable": True, "charmable": False}, "authority": {"clearance_level": 2, "can_grant_access": ["fleet_operations"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_general_novoc_coorg", "name": "General Novoc Coorg", "rarity": "rare", "aliases": ["General Coorg"], "faction_id": "new_republic", "role": "Military General", "archetype": "Strategist", "traits": ["Cautious", "Experienced", "Weary"], "motivation": "Protect soldiers under command", "secret": "Questions war's necessity", "voice_tags": ["weary", "formal"], "default_location_id": "loc-war_college", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 3, "can_grant_access": ["military_command"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_fleet_admin_kosh", "name": "Fleet Administrator Kosh", "rarity": "rare", "aliases": ["Administrator Kosh"], "faction_id": "new_republic", "role": "Logistics Officer", "archetype": "Administrator", "traits": ["Meticulous", "Frustrated", "Competent"], "motivation": "Keep fleet supplied", "secret": "Blackmails suppliers for discounts", "voice_tags": ["formal", "measured"], "default_location_id": "loc-fleet_base_orbital", "levers": {"bribeable": True, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 1, "can_grant_access": ["supply_operations"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_lieutenant_kell_tainer", "name": "Lieutenant Kell Tainer", "rarity": "rare", "aliases": ["Lieutenant Tainer"], "faction_id": "new_republic", "role": "Military Officer", "archetype": "Soldier", "traits": ["Brave", "Loyal", "Straightforward"], "motivation": "Protect Republic and soldiers", "secret": "In love with fellow officer", "voice_tags": ["earnest", "straightforward"], "default_location_id": "loc-fleet_base_orbital", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["military_base"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_aide_marath_bal", "name": "Aide Marath Bal", "rarity": "rare", "aliases": ["Aide Bal"], "faction_id": "new_republic", "role": "Political Aide", "archetype": "Clerk", "traits": ["Ambitious", "Gossip", "Connected"], "motivation": "Climb political ladder", "secret": "Spreads secrets for personal gain", "voice_tags": ["chatty", "formal"], "default_location_id": "loc-coruscant", "levers": {"bribeable": True, "intimidatable": True, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["senate"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},

        # Imperial Remnant (12)
        {"id": "npc_commander_thrass", "name": "Commander Thrass", "rarity": "rare", "aliases": ["Thrass"], "faction_id": "imperial_remnant", "role": "Military Officer", "archetype": "Soldier", "traits": ["Analytical", "Cunning", "Principled"], "motivation": "Restore Imperial greatness", "secret": "Doubts Thrawn's strategy", "voice_tags": ["measured", "analytical"], "default_location_id": "loc-bastion", "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 2, "can_grant_access": ["imperial_military"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_captain_pelleon", "name": "Captain Pelleon", "rarity": "rare", "aliases": ["Captain Pelleon"], "faction_id": "imperial_remnant", "role": "Military Officer", "archetype": "Pilot", "traits": ["Honorable", "Professional", "Traditional"], "motivation": "Restore Imperial Navy", "secret": "Questions extreme tactics", "voice_tags": ["formal", "measured"], "default_location_id": "loc-chimaera", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 2, "can_grant_access": ["imperial_military"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_colonel_tierce", "name": "Colonel Tierce", "rarity": "rare", "aliases": ["Colonel Tierce"], "faction_id": "imperial_remnant", "role": "Military Officer", "archetype": "Soldier", "traits": ["Ruthless", "Tactical", "Ambitious"], "motivation": "Rise through hierarchy", "secret": "Secretly ambitious for own command", "voice_tags": ["commanding", "cold"], "default_location_id": "loc-bastion", "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 2, "can_grant_access": ["imperial_military"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_agent_ferris", "name": "Agent Ferris", "rarity": "rare", "aliases": ["Agent"], "faction_id": "imperial_remnant", "role": "Intelligence Agent", "archetype": "Spy", "traits": ["Cunning", "Merciless", "Thorough"], "motivation": "Protect Remnant through intelligence", "secret": "Has embedded Republic agents", "voice_tags": ["quiet", "measured"], "default_location_id": "loc-bastion", "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 2, "can_grant_access": ["intelligence_network"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_lord_vilrek", "name": "Lord Commander Vil'rek", "rarity": "rare", "aliases": ["Vil'rek"], "faction_id": "imperial_remnant", "role": "Military Lord", "archetype": "Warlord", "traits": ["Arrogant", "Powerful", "Brutal"], "motivation": "Expand personal power", "secret": "Plots against Grand Admiral Thrawn", "voice_tags": ["commanding", "arrogant"], "default_location_id": "loc-bilbringi", "levers": {"bribeable": True, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 3, "can_grant_access": ["imperial_military"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_captain_fyr_renning", "name": "Captain Fyr Renning", "rarity": "rare", "aliases": ["Captain Renning"], "faction_id": "imperial_remnant", "role": "Star Destroyer Captain", "archetype": "Pilot", "traits": ["Skilled", "Loyal", "Disciplined"], "motivation": "Serve the Remnant", "secret": "Has doubts about Remnant victory", "voice_tags": ["formal", "measured"], "default_location_id": "loc-bastion", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 2, "can_grant_access": ["imperial_military"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_general_sarm_krief", "name": "General Sarm Krief", "rarity": "rare", "aliases": ["General Krief"], "faction_id": "imperial_remnant", "role": "Military General", "archetype": "Strategist", "traits": ["Experienced", "Cautious", "Political"], "motivation": "Preserve Remnant military", "secret": "Negotiates secretly with New Republic", "voice_tags": ["formal", "measured"], "default_location_id": "loc-bastion", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 3, "can_grant_access": ["imperial_military"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_agent_storax", "name": "Agent Storax", "rarity": "rare", "aliases": ["Agent"], "faction_id": "imperial_remnant", "role": "Intelligence Agent", "archetype": "Spy", "traits": ["Paranoid", "Cautious", "Thorough"], "motivation": "Root out Republic infiltration", "secret": "Is secretly Republic agent", "voice_tags": ["quiet", "suspicious"], "default_location_id": "loc-bastion", "levers": {"bribeable": False, "intimidatable": True, "charmable": False}, "authority": {"clearance_level": 2, "can_grant_access": ["intelligence_network"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_commodore_dillenbeck", "name": "Commodore Dillenbeck", "rarity": "rare", "aliases": ["Commodore"], "faction_id": "imperial_remnant", "role": "Fleet Officer", "archetype": "Pilot", "traits": ["Professional", "Ambitious", "Calculating"], "motivation": "Advance through ranks", "secret": "Accepts bribes for military contracts", "voice_tags": ["formal", "measured"], "default_location_id": "loc-bilbringi", "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 2, "can_grant_access": ["imperial_military"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_defector_commander_vex", "name": "Defector Commander Vex", "rarity": "rare", "aliases": ["Commander Vex"], "faction_id": "new_republic", "role": "Military Officer", "archetype": "Soldier", "traits": ["Conflicted", "Skilled", "Seeking Redemption"], "motivation": "Seek redemption for past Imperial service", "secret": "Still sympathizes with some Imperial ideals", "voice_tags": ["measured", "formal"], "default_location_id": "loc-fleet_base_orbital", "levers": {"bribeable": False, "intimidatable": True, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["military_base"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_adjutant_kris", "name": "Adjutant Kris", "rarity": "rare", "aliases": ["Kris"], "faction_id": "imperial_remnant", "role": "Officer's Aide", "archetype": "Clerk", "traits": ["Efficient", "Loyal", "Observant"], "motivation": "Serve with loyalty and precision", "secret": "Keeps records of command corruption", "voice_tags": ["formal", "measured"], "default_location_id": "loc-bastion", "levers": {"bribeable": False, "intimidatable": True, "charmable": False}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},

        # Jedi Academy Personnel (10)
        {"id": "npc_master_cilghal", "name": "Master Cilghal", "rarity": "rare", "aliases": ["Cilghal"], "faction_id": "jedi_order", "role": "Jedi Master", "archetype": "Force User", "traits": ["Wise", "Compassionate", "Skilled"], "motivation": "Heal students and teach Jedi ways", "secret": "Harbors doubts about Luke's leadership", "voice_tags": ["measured", "wise"], "default_location_id": "loc-yavin_praxeum", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 3, "can_grant_access": ["jedi_academy"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_acolyte_tyria_sarkin", "name": "Acolyte Tyria Sarkin", "rarity": "rare", "aliases": ["Tyria"], "faction_id": "jedi_order", "role": "Jedi Acolyte", "archetype": "Force User", "traits": ["Eager", "Powerful", "Impulsive"], "motivation": "Master the Force and become Jedi", "secret": "Struggles with anger and aggressive impulses", "voice_tags": ["earnest", "determined"], "default_location_id": "loc-yavin_praxeum", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["jedi_academy"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_streen", "name": "Streen", "rarity": "rare", "aliases": ["Streen"], "faction_id": "jedi_order", "role": "Jedi Adept", "archetype": "Force User", "traits": ["Quiet", "Withdrawn", "Powerful"], "motivation": "Find peace through the Force", "secret": "Hears constant Force whispers", "voice_tags": ["quiet", "mysterious"], "default_location_id": "loc-yavin_praxeum", "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 1, "can_grant_access": ["jedi_academy"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_master_kam_solusar", "name": "Master Kam Solusar", "rarity": "rare", "aliases": ["Kam"], "faction_id": "jedi_order", "role": "Jedi Master", "archetype": "Force User", "traits": ["Skilled", "Patient", "Haunted"], "motivation": "Train next generation of Jedi", "secret": "Was once with the Sith", "voice_tags": ["formal", "measured"], "default_location_id": "loc-yavin_praxeum", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 3, "can_grant_access": ["jedi_academy"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_master_kirana_ti", "name": "Master Kirana Ti", "rarity": "rare", "aliases": ["Kirana"], "faction_id": "jedi_order", "role": "Jedi Master", "archetype": "Force User", "traits": ["Fierce", "Strong", "Protective"], "motivation": "Protect Jedi and teach combat", "secret": "Was forced to abandon previous life", "voice_tags": ["commanding", "determined"], "default_location_id": "loc-yavin_praxeum", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 3, "can_grant_access": ["jedi_academy"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_dorsk_81", "name": "Dorsk 81", "rarity": "rare", "aliases": ["81"], "faction_id": "jedi_order", "role": "Jedi Adept", "archetype": "Force User", "traits": ["Alien", "Curious", "Different"], "motivation": "Understand humanity and the Force", "secret": "Feels isolated due to non-human nature", "voice_tags": ["measured", "formal"], "default_location_id": "loc-yavin_praxeum", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["jedi_academy"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_jedi_emissary_tonith", "name": "Jedi Emissary Tonith", "rarity": "rare", "aliases": ["Tonith"], "faction_id": "jedi_order", "role": "Jedi Emissary", "archetype": "Force User", "traits": ["Diplomatic", "Perceptive", "Calm"], "motivation": "Maintain Jedi peace and influence", "secret": "Manipulates events for greater good", "voice_tags": ["diplomatic", "measured"], "default_location_id": "loc-coruscant", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 2, "can_grant_access": ["jedi_operations"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_healer_yeveth", "name": "Healer Yeveth", "rarity": "rare", "aliases": ["Yeveth"], "faction_id": "jedi_order", "role": "Jedi Healer", "archetype": "Force User", "traits": ["Compassionate", "Focused", "Serene"], "motivation": "Heal the wounded and teach healing", "secret": "Has love for student", "voice_tags": ["compassionate", "measured"], "default_location_id": "loc-yavin_praxeum", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["jedi_academy"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
        {"id": "npc_student_valin_horn", "name": "Student Valin Horn", "rarity": "rare", "aliases": ["Valin"], "faction_id": "jedi_order", "role": "Jedi Student", "archetype": "Force User", "traits": ["Enthusiastic", "Talented", "Stubborn"], "motivation": "Become greatest Jedi ever", "secret": "Doubts whether he is worthy", "voice_tags": ["earnest", "enthusiastic"], "default_location_id": "loc-yavin_praxeum", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 0, "can_grant_access": ["jedi_academy"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    ]

    npcs['rotating'].extend(rotating_npcs)
    print(f"Added {len(rotating_npcs)} rotating NPCs. Total rotating: {len(npcs['rotating'])}")

    # Save progress
    with open('data/static/era_packs/new_republic/npcs.yaml', 'w', encoding='utf-8') as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    total_count = sum(len(v) for v in npcs.values() if isinstance(v, list))
    added_count = total_count - initial_count
    print(f"\nProgress: {total_count} total NPCs ({added_count} added so far)")
    print(f"  Anchors: {len(npcs['anchors'])}")
    print(f"  Rotating: {len(npcs['rotating'])}")
    print(f"  Templates: {len(npcs['templates'])}")

if __name__ == "__main__":
    main()
