# -*- coding: utf-8 -*-
"""Third batch: Procedural NPC Templates"""

import yaml

with open('data/static/era_packs/new_republic/npcs.yaml', 'r', encoding='utf-8') as f:
    data = yaml.safe_load(f)

npcs = data['npcs']
initial = sum(len(v) for v in npcs.values() if isinstance(v, list))

# 17 new procedural templates
template_npcs = [
    {"id": "nr_navy_officer_template", "role": "Navy Officer", "archetype": "Pilot", "traits": ["professional", "disciplined"], "motivations": ["Serve New Republic"], "secrets": ["Personal ambitions beyond military"], "voice_tags": ["formal", "measured"], "species": ["Human", "Mon Calamari"], "tags": ["republic", "military"], "namebank": "republic_names", "spawn": {"location_tags_any": ["republic", "military"], "location_types_any": ["fleet_base"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["fleet_operations"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "jedi_academy_student_template", "role": "Jedi Student", "archetype": "Force User", "traits": ["eager", "determined"], "motivations": ["Master the Force"], "secrets": ["Self-doubt about Force abilities"], "voice_tags": ["earnest", "enthusiastic"], "species": ["Human", "Zabrak"], "tags": ["jedi", "force"], "namebank": "jedi_names", "spawn": {"location_tags_any": ["jedi", "force"], "location_types_any": ["temple"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["jedi_academy"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "imperial_remnant_soldier_template", "role": "Imperial Soldier", "archetype": "Soldier", "traits": ["loyal", "disciplined"], "motivations": ["Restore Imperial glory"], "secrets": ["Doubts about ultimate victory"], "voice_tags": ["formal", "cold"], "species": ["Human", "Chiss"], "tags": ["imperial", "military"], "namebank": "imperial_names", "spawn": {"location_tags_any": ["imperial"], "location_types_any": ["military_base"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "imperial_officer_template", "role": "Imperial Officer", "archetype": "Strategist", "traits": ["analytical", "ambitious"], "motivations": ["Rise through ranks"], "secrets": ["Frustration with bureaucracy"], "voice_tags": ["formal", "calculated"], "species": ["Human", "Chiss"], "tags": ["imperial", "command"], "namebank": "imperial_officer_names", "spawn": {"location_tags_any": ["imperial", "command"], "location_types_any": ["command_ship"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 2, "can_grant_access": ["imperial_command"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "frontier_colonist_template", "role": "Frontier Settler", "archetype": "Laborer", "traits": ["pragmatic", "resourceful"], "motivations": ["Build new life"], "secrets": ["Fleeing troubled past"], "voice_tags": ["informal", "practical"], "species": ["Human", "Zabrak"], "tags": ["frontier", "colonial"], "namebank": "frontier_names", "spawn": {"location_tags_any": ["frontier"], "location_types_any": ["settlement"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": False, "intimidatable": True, "charmable": True}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "spy_agent_template", "role": "Intelligence Agent", "archetype": "Spy", "traits": ["cunning", "paranoid"], "motivations": ["Gather intelligence"], "secrets": ["True allegiance unclear"], "voice_tags": ["quiet", "measured"], "species": ["Human"], "tags": ["intelligence", "spy"], "namebank": "common_names", "spawn": {"location_tags_any": ["intelligence"], "location_types_any": [], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": False, "intimidatable": True, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "corporate_executive_template", "role": "Corporate Executive", "archetype": "Entrepreneur", "traits": ["ruthless", "ambitious"], "motivations": ["Maximize profits"], "secrets": ["Unethical business practices"], "voice_tags": ["formal", "calculating"], "species": ["Human"], "tags": ["corporate", "business"], "namebank": "corporate_names", "spawn": {"location_tags_any": ["corporate"], "location_types_any": ["headquarters"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["corporate_resources"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "archaeologist_template", "role": "Archaeologist", "archetype": "Scholar", "traits": ["obsessed", "brilliant"], "motivations": ["Uncover ancient mysteries"], "secrets": ["Gray areas in artifact ethics"], "voice_tags": ["academic", "enthusiastic"], "species": ["Human", "Zabrak"], "tags": ["scholar", "academic"], "namebank": "scholar_names", "spawn": {"location_tags_any": ["archaeological"], "location_types_any": ["dig_site"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["research_facilities"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "smuggler_independent_template", "role": "Independent Smuggler", "archetype": "Scoundrel", "traits": ["cunning", "pragmatic"], "motivations": ["Make profits"], "secrets": ["Connections to larger networks"], "voice_tags": ["informal", "calculating"], "species": ["Human", "Rodian"], "tags": ["smuggler", "underworld"], "namebank": "smuggler_names", "spawn": {"location_tags_any": ["underworld"], "location_types_any": ["cantina"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": True, "intimidatable": True, "charmable": True}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "black_sun_member_template", "role": "Black Sun Operative", "archetype": "Criminal", "traits": ["ruthless", "ambitious"], "motivations": ["Advance within Black Sun"], "secrets": ["Methods for accumulating power"], "voice_tags": ["menacing", "formal"], "species": ["Human", "Zabrak"], "tags": ["black_sun", "criminal"], "namebank": "criminal_names", "spawn": {"location_tags_any": ["black_sun"], "location_types_any": [], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": True, "intimidatable": True, "charmable": False}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "jedi_master_template", "role": "Jedi Master", "archetype": "Force User", "traits": ["wise", "patient"], "motivations": ["Train Jedi students"], "secrets": ["Doubts about Jedi philosophy"], "voice_tags": ["measured", "wise"], "species": ["Human", "Mon Calamari"], "tags": ["jedi", "master"], "namebank": "jedi_master_names", "spawn": {"location_tags_any": ["jedi"], "location_types_any": ["temple"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 3, "can_grant_access": ["jedi_academy"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "bounty_hunter_template", "role": "Bounty Hunter", "archetype": "Mercenary", "traits": ["skilled", "pragmatic"], "motivations": ["Complete contracts"], "secrets": ["Personal code of honor"], "voice_tags": ["professional", "calculating"], "species": ["Human", "Trandoshan"], "tags": ["bounty_hunter", "mercenary"], "namebank": "mercenary_names", "spawn": {"location_tags_any": ["bounty_hunter"], "location_types_any": ["cantina"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": True, "intimidatable": True, "charmable": True}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "diplomat_template", "role": "Diplomat", "archetype": "Negotiator", "traits": ["eloquent", "perceptive"], "motivations": ["Negotiate treaties"], "secrets": ["Romantic entanglements"], "voice_tags": ["diplomatic", "thoughtful"], "species": ["Human", "Mon Calamari"], "tags": ["diplomat", "political"], "namebank": "diplomat_names", "spawn": {"location_tags_any": ["diplomatic"], "location_types_any": ["embassy"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["diplomatic_missions"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "sensor_tech_template", "role": "Sensor Technician", "archetype": "Technician", "traits": ["detail-oriented", "analytical"], "motivations": ["Maintain systems"], "secrets": ["Information they could sell"], "voice_tags": ["formal", "technical"], "species": ["Human", "Sullustan"], "tags": ["technician", "military"], "namebank": "tech_names", "spawn": {"location_tags_any": ["military"], "location_types_any": ["command_center"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["command_systems"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "pilot_elite_template", "role": "Elite Pilot", "archetype": "Pilot", "traits": ["skilled", "confident"], "motivations": ["Fly best ships"], "secrets": ["Hiding past failures"], "voice_tags": ["confident", "formal"], "species": ["Human", "Sullustan"], "tags": ["pilot", "military"], "namebank": "pilot_names", "spawn": {"location_tags_any": ["military", "pilot"], "location_types_any": ["flight_base"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["flight_operations"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "scoundrel_template", "role": "Scoundrel", "archetype": "Scoundrel", "traits": ["charming", "deceptive"], "motivations": ["Make fast credits"], "secrets": ["Hidden romantic entanglements"], "voice_tags": ["informal", "charming"], "species": ["Human", "Rodian"], "tags": ["scoundrel", "underworld"], "namebank": "scoundrel_names", "spawn": {"location_tags_any": ["underworld"], "location_types_any": ["cantina"], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": True, "intimidatable": True, "charmable": True}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "force_sensitive_template", "role": "Force Sensitive", "archetype": "Force User", "traits": ["sensitive", "conflicted"], "motivations": ["Understand Force connection"], "secrets": ["Hiding Force sensitivity"], "voice_tags": ["thoughtful", "measured"], "species": ["Human", "Zabrak"], "tags": ["force", "sensitive"], "namebank": "common_names", "spawn": {"location_tags_any": [], "location_types_any": [], "min_alert": 0, "max_alert": 100}, "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
]

npcs['templates'].extend(template_npcs)

print(f"Added {len(template_npcs)} new procedural templates")
print(f"Templates now: {len(npcs['templates'])}")

# Save
with open('data/static/era_packs/new_republic/npcs.yaml', 'w', encoding='utf-8') as f:
    yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

new_total = sum(len(v) for v in npcs.values() if isinstance(v, list))
print(f"Total NPCs: {new_total}")
print(f"  Anchors: {len(npcs['anchors'])}")
print(f"  Rotating: {len(npcs['rotating'])}")
print(f"  Templates: {len(npcs['templates'])}")
