# -*- coding: utf-8 -*-
"""Second batch: Frontier & Colonial Leaders + Merchants/Traders/Smugglers"""

import yaml

with open('data/static/era_packs/new_republic/npcs.yaml', 'r', encoding='utf-8') as f:
    data = yaml.safe_load(f)

npcs = data['npcs']
initial = sum(len(v) for v in npcs.values() if isinstance(v, list))

# Frontier & Colonial Leaders (10)
frontier_npcs = [
    {"id": "npc_governor_saldor_tann", "name": "Governor Saldor Tann", "rarity": "rare", "aliases": ["Governor Tann"], "faction_id": "new_republic", "role": "Colonial Governor", "archetype": "Administrator", "traits": ["Authoritarian", "Practical", "Isolationist"], "motivation": "Keep colony independent and secure", "secret": "Hoards resources against starvation", "voice_tags": ["commanding", "formal"], "default_location_id": "loc-frontier_settlement", "levers": {"bribeable": True, "intimidatable": True, "charmable": False}, "authority": {"clearance_level": 2, "can_grant_access": ["colony_settlement"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_settlement_leader_mika", "name": "Settlement Leader Mika", "rarity": "rare", "aliases": ["Mika"], "faction_id": "new_republic", "role": "Settlement Leader", "archetype": "Administrator", "traits": ["Fair", "Community-Focused", "Optimistic"], "motivation": "Build thriving community", "secret": "Covers up crime to maintain hope", "voice_tags": ["earnest", "diplomatic"], "default_location_id": "loc-exploration_outpost", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["settlement"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_archaeologist_dr_venn", "name": "Archaeologist Dr. Venn", "rarity": "rare", "aliases": ["Doctor Venn"], "faction_id": "new_republic", "role": "Archaeologist", "archetype": "Scholar", "traits": ["Obsessed", "Brilliant", "Reckless"], "motivation": "Uncover ancient galactic history", "secret": "Grave-robs and falsifies findings", "voice_tags": ["academic", "enthusiastic"], "default_location_id": "loc-archaeological_dig", "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["archaeological_sites"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_militia_commander_ketis", "name": "Colonial Militia Commander Ketis", "rarity": "rare", "aliases": ["Commander Ketis"], "faction_id": "new_republic", "role": "Militia Commander", "archetype": "Soldier", "traits": ["Tough", "Pragmatic", "Weary"], "motivation": "Protect frontier settlement", "secret": "Has made peace with local raiders", "voice_tags": ["gruff", "formal"], "default_location_id": "loc-frontier_settlement", "levers": {"bribeable": False, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 1, "can_grant_access": ["militia"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_engineer_rask", "name": "Ecological Engineer Rask", "rarity": "rare", "aliases": ["Rask"], "faction_id": "new_republic", "role": "Environmental Engineer", "archetype": "Technician", "traits": ["Passionate", "Idealistic", "Frustrated"], "motivation": "Terraform and restore worlds", "secret": "Sabotages damaging development", "voice_tags": ["earnest", "passionate"], "default_location_id": "loc-research_station", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["research_station"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_scout_leader_yevin", "name": "Scout Leader Yevin", "rarity": "rare", "aliases": ["Yevin"], "faction_id": "new_republic", "role": "Scout Leader", "archetype": "Explorer", "traits": ["Adventurous", "Skilled", "Independent"], "motivation": "Explore unknown regions", "secret": "Has gone native with alien tribe", "voice_tags": ["earnest", "adventurous"], "default_location_id": "loc-frontier_settlement", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["exploration_routes"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_administrator_coles", "name": "Administrator Coles", "rarity": "rare", "aliases": ["Coles"], "faction_id": "new_republic", "role": "Colonial Administrator", "archetype": "Clerk", "traits": ["Meticulous", "Bureaucratic", "Frustrated"], "motivation": "Maintain colony records and order", "secret": "Embezzles colony resources", "voice_tags": ["formal", "measured"], "default_location_id": "loc-frontier_settlement", "levers": {"bribeable": True, "intimidatable": True, "charmable": False}, "authority": {"clearance_level": 1, "can_grant_access": ["colony_records"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_outpost_chief_brin", "name": "Outpost Chief Brin", "rarity": "rare", "aliases": ["Chief Brin"], "faction_id": "new_republic", "role": "Outpost Chief", "archetype": "Administrator", "traits": ["Practical", "Friendly", "Resourceful"], "motivation": "Keep remote outpost functioning", "secret": "Runs black market trade through outpost", "voice_tags": ["informal", "friendly"], "default_location_id": "loc-exploration_outpost", "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["outpost"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_settler_elder_carla", "name": "Settler Elder Carla", "rarity": "rare", "aliases": ["Elder Carla"], "faction_id": "new_republic", "role": "Community Elder", "archetype": "Advisor", "traits": ["Wise", "Traditional", "Protective"], "motivation": "Preserve community traditions", "secret": "Enforces harsh traditional punishments", "voice_tags": ["wise", "formal"], "default_location_id": "loc-frontier_settlement", "levers": {"bribeable": False, "intimidatable": True, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["community_decisions"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_trade_commissioner_yorrin", "name": "Trade Commissioner Yorrin", "rarity": "rare", "aliases": ["Commissioner Yorrin"], "faction_id": "new_republic", "role": "Trade Commissioner", "archetype": "Merchant", "traits": ["Shrewd", "Profit-Focused", "Connected"], "motivation": "Maximize trade profits", "secret": "Manipulates commodity prices", "voice_tags": ["calculated", "formal"], "default_location_id": "loc-trade_hub", "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["trade_routes"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
]

# Merchants & Smugglers (10)
merchant_npcs = [
    {"id": "npc_trader_captain_drell_kasnov", "name": "Trader Captain Drell Kasnov", "rarity": "rare", "aliases": ["Captain Kasnov"], "faction_id": "smugglers_alliance", "role": "Trader Captain", "archetype": "Merchant", "traits": ["Entrepreneurial", "Cautious", "Worldly"], "motivation": "Build successful trading business", "secret": "Smuggles illegal goods alongside legitimate trade", "voice_tags": ["formal", "measured"], "default_location_id": "loc-trade_hub", "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["trade_network"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_info_broker_kess", "name": "Information Broker Kess", "rarity": "rare", "aliases": ["Kess"], "faction_id": "underworld", "role": "Information Broker", "archetype": "Dealer", "traits": ["Knowledgeable", "Neutral", "Careful"], "motivation": "Accumulate valuable information", "secret": "Sells information to both NR and Remnant", "voice_tags": ["calculated", "measured"], "default_location_id": "loc-pesegam", "levers": {"bribeable": True, "intimidatable": False, "charmable": False}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_smuggler_reis_korven", "name": "Smuggler Reis Korven", "rarity": "rare", "aliases": ["Reis"], "faction_id": "smugglers_alliance", "role": "Smuggler", "archetype": "Scoundrel", "traits": ["Reformed", "Skilled", "Protective"], "motivation": "Leave smuggling life and protect loved ones", "secret": "Cannot fully leave smuggling behind", "voice_tags": ["informal", "earnest"], "default_location_id": "loc-myrkr", "levers": {"bribeable": False, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_corporate_exec_vex_alcar", "name": "Corporate Executive Vex Alcar", "rarity": "rare", "aliases": ["Executive Alcar"], "faction_id": "neutral", "role": "Corporate Executive", "archetype": "Entrepreneur", "traits": ["Ruthless", "Ambitious", "Wealthy"], "motivation": "Maximize corporate profits", "secret": "Funds both NR and Remnant for profit", "voice_tags": ["formal", "calculating"], "default_location_id": "loc-corporate_hub", "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 1, "can_grant_access": ["corporate_network"]}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_blackmarket_fence_mirala", "name": "Black Market Fence Mirala", "rarity": "rare", "aliases": ["Mirala"], "faction_id": "underworld", "role": "Black Market Dealer", "archetype": "Dealer", "traits": ["Cunning", "Ruthless", "Connected"], "motivation": "Control black market operations", "secret": "Employs former Republic soldiers", "voice_tags": ["quiet", "calculating"], "default_location_id": "loc-pesegam", "levers": {"bribeable": True, "intimidatable": True, "charmable": False}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_smuggler_captain_zekka", "name": "Smuggler Captain Zekka", "rarity": "rare", "aliases": ["Captain Zekka"], "faction_id": "smugglers_alliance", "role": "Smuggler Captain", "archetype": "Scoundrel", "traits": ["Daring", "Skilled", "Greedy"], "motivation": "Make profits through dangerous smuggling", "secret": "Transports wanted criminals", "voice_tags": ["informal", "bold"], "default_location_id": "loc-myrkr", "levers": {"bribeable": True, "intimidatable": True, "charmable": True}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_spice_trader_lord_pax", "name": "Spice Trader Lord Pax", "rarity": "rare", "aliases": ["Lord Pax"], "faction_id": "underworld", "role": "Spice Trader", "archetype": "Dealer", "traits": ["Addicted", "Paranoid", "Powerful"], "motivation": "Control spice trade and protect operations", "secret": "Enslaves spice workers", "voice_tags": ["nervous", "paranoid"], "default_location_id": "loc-kessel", "levers": {"bribeable": True, "intimidatable": True, "charmable": False}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_ship_broker_kellyan", "name": "Ship Broker Kellyan", "rarity": "rare", "aliases": ["Kellyan"], "faction_id": "neutral", "role": "Ship Broker", "archetype": "Merchant", "traits": ["Well-Connected", "Shrewd", "Professional"], "motivation": "Facilitate ship sales for profit", "secret": "Sells salvage titles for stolen ships", "voice_tags": ["formal", "measured"], "default_location_id": "loc-trade_hub", "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_caravan_master_orn", "name": "Caravan Master Orn", "rarity": "rare", "aliases": ["Master Orn"], "faction_id": "neutral", "role": "Caravan Master", "archetype": "Trader", "traits": ["Experienced", "Fair", "Protective"], "motivation": "Lead profitable caravans safely", "secret": "Pays off bandits to avoid conflict", "voice_tags": ["formal", "practical"], "default_location_id": "loc-trade_hub", "levers": {"bribeable": True, "intimidatable": False, "charmable": True}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
    {"id": "npc_underboss_krell", "name": "Underboss Krell", "rarity": "rare", "aliases": ["Krell"], "faction_id": "underworld", "role": "Crime Underboss", "archetype": "Dealer", "traits": ["Tough", "Ruthless", "Cunning"], "motivation": "Control criminal operations", "secret": "Reporting to higher crime boss", "voice_tags": ["commanding", "gruff"], "default_location_id": "loc-pesegam", "levers": {"bribeable": True, "intimidatable": True, "charmable": False}, "authority": {"clearance_level": 0, "can_grant_access": []}, "knowledge": {"rumors": [], "quest_facts": [], "secrets": []}},
]

npcs['rotating'].extend(frontier_npcs)
npcs['rotating'].extend(merchant_npcs)

print(f"Added {len(frontier_npcs)} frontier NPCs")
print(f"Added {len(merchant_npcs)} merchant NPCs")
print(f"Rotating NPCs now: {len(npcs['rotating'])}")

# Save
with open('data/static/era_packs/new_republic/npcs.yaml', 'w', encoding='utf-8') as f:
    yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

new_total = sum(len(v) for v in npcs.values() if isinstance(v, list))
print(f"Total NPCs: {new_total}")
